export const houseTypesData = [
  {
    id: 1,
    name: "Acacia",
    slug: "acacia",
    location: "Maitama, Lagos",
    price: 4500,
    description: "Experience luxury living in our Acacia collection. A sophisticated residence featuring modern architecture with premium finishes, spacious interiors, and seamless indoor-outdoor flow.",
    beds: 4,
    baths: 3,
    sqft: 1589,
    amenities: [
      { name: "Infinity Pool", icon: "droplet" },
      { name: "Ocean View", icon: "eye" },
      { name: "Beach Access", icon: "waves" },
      { name: "Workspace", icon: "briefcase" },
      { name: "Fitness", icon: "dumbbell" },
      { name: "Wifi", icon: "wifi" },
    ],
    floors: [
      { name: "Floor 1", image: "/placeholder-floor-1.jpg" },
      { name: "Floor 2", image: "/placeholder-floor-2.jpg" },
    ],
    priceHistory: { labels: ["2020", "2021", "2022", "2023", "2024"], data: [2500, 3000, 3500, 4000, 4500] },
    agent: { name: "Emily Johnson", company: "Skyline Realty Group", rating: 5 },
  },
  {
    id: 2,
    name: "Oakville",
    slug: "oakville",
    location: "Victoria Island, Lagos",
    price: 5200,
    description: "Discover contemporary elegance at Oakville. This modern residential masterpiece combines architectural excellence with luxury amenities, creating an unparalleled living experience.",
    beds: 5,
    baths: 4,
    sqft: 2100,
    amenities: [
      { name: "Infinity Pool", icon: "droplet" },
      { name: "City View", icon: "eye" },
      { name: "Gym", icon: "dumbbell" },
      { name: "Home Office", icon: "briefcase" },
      { name: "Smart Home", icon: "zap" },
      { name: "Concierge", icon: "user" },
    ],
    floors: [
      { name: "Floor 1", image: "/placeholder-floor-1.jpg" },
      { name: "Floor 2", image: "/placeholder-floor-2.jpg" },
    ],
    priceHistory: { labels: ["2020", "2021", "2022", "2023", "2024"], data: [3200, 3800, 4400, 4800, 5200] },
    agent: { name: "James Mitchell", company: "Elite Properties", rating: 5 },
  },
  {
    id: 3,
    name: "Maple",
    slug: "maple",
    location: "Ikoyi, Lagos",
    price: 4800,
    description: "Step into refined living with our Maple collection. Featuring warm architectural elements and premium craftsmanship, this residence offers the perfect balance of comfort and luxury.",
    beds: 4,
    baths: 3,
    sqft: 1750,
    amenities: [
      { name: "Heated Pool", icon: "droplet" },
      { name: "Garden View", icon: "leaf" },
      { name: "Sauna", icon: "flame" },
      { name: "Library", icon: "book" },
      { name: "Wine Cellar", icon: "wine" },
      { name: "Security", icon: "shield" },
    ],
    floors: [
      { name: "Floor 1", image: "/placeholder-floor-1.jpg" },
      { name: "Floor 2", image: "/placeholder-floor-2.jpg" },
    ],
    priceHistory: { labels: ["2020", "2021", "2022", "2023", "2024"], data: [2800, 3400, 3900, 4400, 4800] },
    agent: { name: "Sarah Williams", company: "Luxury Living Realty", rating: 5 },
  },
  {
    id: 4,
    name: "Pine",
    slug: "pine",
    location: "Lekki, Lagos",
    price: 3900,
    description: "Embrace natural elegance with Pine. This environmentally conscious residence blends sustainable design with modern luxury, featuring large windows and abundant natural light.",
    beds: 3,
    baths: 2,
    sqft: 1400,
    amenities: [
      { name: "Garden", icon: "leaf" },
      { name: "Terrace", icon: "sun" },
      { name: "Eco-System", icon: "leaf" },
      { name: "Yoga Studio", icon: "activity" },
      { name: "Meditation", icon: "zap" },
      { name: "Solar Panels", icon: "sun" },
    ],
    floors: [
      { name: "Floor 1", image: "/placeholder-floor-1.jpg" },
      { name: "Floor 2", image: "/placeholder-floor-2.jpg" },
    ],
    priceHistory: { labels: ["2020", "2021", "2022", "2023", "2024"], data: [2100, 2700, 3200, 3600, 3900] },
    agent: { name: "Michael Brown", company: "Green Living Properties", rating: 4.8 },
  },
  {
    id: 5,
    name: "Château",
    slug: "chateau",
    location: "Abuja, FCT",
    price: 6500,
    description: "Experience opulence with our Château collection. Inspired by European architecture, this grand residence features soaring ceilings, marble accents, and unparalleled grandeur.",
    beds: 6,
    baths: 5,
    sqft: 3200,
    amenities: [
      { name: "Grand Foyer", icon: "home" },
      { name: "Wine Room", icon: "wine" },
      { name: "Cinema", icon: "film" },
      { name: "Spa", icon: "droplet" },
      { name: "Chef's Kitchen", icon: "chef" },
      { name: "Ballroom", icon: "music" },
    ],
    floors: [
      { name: "Ground Floor", image: "/placeholder-floor-1.jpg" },
      { name: "First Floor", image: "/placeholder-floor-2.jpg" },
      { name: "Second Floor", image: "/placeholder-floor-3.jpg" },
    ],
    priceHistory: { labels: ["2020", "2021", "2022", "2023", "2024"], data: [4500, 5200, 5800, 6200, 6500] },
    agent: { name: "Victoria Stone", company: "Premier Estates", rating: 5 },
  },
  {
    id: 6,
    name: "Villa",
    slug: "villa",
    location: "Banana Island, Lagos",
    price: 7200,
    description: "Discover the pinnacle of luxury with our Villa collection. Waterfront location with private beach access, infinity pools overlooking the ocean, and world-class amenities.",
    beds: 7,
    baths: 6,
    sqft: 3800,
    amenities: [
      { name: "Private Beach", icon: "waves" },
      { name: "Infinity Pool", icon: "droplet" },
      { name: "Yacht Dock", icon: "anchor" },
      { name: "Helipad", icon: "copter" },
      { name: "Private Theater", icon: "film" },
      { name: "Wellness Center", icon: "heart" },
    ],
    floors: [
      { name: "Ground Floor", image: "/placeholder-floor-1.jpg" },
      { name: "First Floor", image: "/placeholder-floor-2.jpg" },
      { name: "Penthouse", image: "/placeholder-floor-3.jpg" },
    ],
    priceHistory: { labels: ["2020", "2021", "2022", "2023", "2024"], data: [5000, 5800, 6400, 6900, 7200] },
    agent: { name: "Alexandra Grant", company: "Exclusive Properties", rating: 5 },
  },
  {
    id: 7,
    name: "Oak",
    slug: "oak",
    location: "Ajah, Lagos",
    price: 4100,
    description: "Timeless sophistication meets modern comfort in our Oak residences. Features classic architectural details with contemporary upgrades for the discerning homeowner.",
    beds: 4,
    baths: 3,
    sqft: 1650,
    amenities: [
      { name: "Library", icon: "book" },
      { name: "Study", icon: "briefcase" },
      { name: "Fireplace", icon: "flame" },
      { name: "Wine Bar", icon: "wine" },
      { name: "Lounge", icon: "chair" },
      { name: "Garden", icon: "leaf" },
    ],
    floors: [
      { name: "Floor 1", image: "/placeholder-floor-1.jpg" },
      { name: "Floor 2", image: "/placeholder-floor-2.jpg" },
    ],
    priceHistory: { labels: ["2020", "2021", "2022", "2023", "2024"], data: [2400, 3000, 3500, 3800, 4100] },
    agent: { name: "David Foster", company: "Heritage Properties", rating: 4.9 },
  },
  {
    id: 8,
    name: "Scarlet Oak",
    slug: "scarlet-oak",
    location: "Parkview, Lagos",
    price: 4600,
    description: "Make a statement with Scarlet Oak. This distinctive residence blends rich colors with bold architectural statements, creating a truly unique and memorable home.",
    beds: 4,
    baths: 3,
    sqft: 1800,
    amenities: [
      { name: "Art Gallery", icon: "palette" },
      { name: "Music Room", icon: "music" },
      { name: "Theater", icon: "film" },
      { name: "Lounge", icon: "chair" },
      { name: "Terrace", icon: "sun" },
      { name: "Bar", icon: "wine" },
    ],
    floors: [
      { name: "Floor 1", image: "/placeholder-floor-1.jpg" },
      { name: "Floor 2", image: "/placeholder-floor-2.jpg" },
    ],
    priceHistory: { labels: ["2020", "2021", "2022", "2023", "2024"], data: [2700, 3300, 3900, 4300, 4600] },
    agent: { name: "Rachel Thompson", company: "Artistic Living", rating: 4.8 },
  },
  {
    id: 9,
    name: "Maple Penthouse",
    slug: "maple-penthouse",
    location: "Ikoyi Heights, Lagos",
    price: 5900,
    description: "Rise above the city in our Maple Penthouse. Panoramic views, skyline access, and premium furnishings create an extraordinary elevated living experience.",
    beds: 4,
    baths: 3,
    sqft: 2400,
    amenities: [
      { name: "Rooftop Terrace", icon: "sun" },
      { name: "Sky Lounge", icon: "chair" },
      { name: "Infinity Pool", icon: "droplet" },
      { name: "Sauna", icon: "flame" },
      { name: "Bar", icon: "wine" },
      { name: "Panoramic Views", icon: "eye" },
    ],
    floors: [
      { name: "Living Level", image: "/placeholder-floor-1.jpg" },
      { name: "Bedroom Level", image: "/placeholder-floor-2.jpg" },
    ],
    priceHistory: { labels: ["2020", "2021", "2022", "2023", "2024"], data: [3800, 4500, 5100, 5500, 5900] },
    agent: { name: "Christopher Lee", company: "Sky High Realty", rating: 5 },
  },
  {
    id: 10,
    name: "Pine Penthouse",
    slug: "pine-penthouse",
    location: "Lekki Phase 2, Lagos",
    price: 5100,
    description: "Sustainable luxury at new heights. This eco-conscious penthouse combines green living with penthouses privileges, featuring solar integration and smart home technology.",
    beds: 3,
    baths: 2,
    sqft: 2000,
    amenities: [
      { name: "Green Roof", icon: "leaf" },
      { name: "Solar System", icon: "sun" },
      { name: "Rainwater Harvest", icon: "droplet" },
      { name: "Rooftop Garden", icon: "leaf" },
      { name: "Meditation Deck", icon: "zap" },
      { name: "Smart Systems", icon: "wifi" },
    ],
    floors: [
      { name: "Main Level", image: "/placeholder-floor-1.jpg" },
      { name: "Sleep Level", image: "/placeholder-floor-2.jpg" },
    ],
    priceHistory: { labels: ["2020", "2021", "2022", "2023", "2024"], data: [3200, 3900, 4400, 4800, 5100] },
    agent: { name: "Nina Patel", company: "Eco-Luxury Living", rating: 4.9 },
  },
  {
    id: 11,
    name: "Olive",
    slug: "olive",
    location: "Eko Atlantic, Lagos",
    price: 6800,
    description: "Timeless elegance meets modern sophistication in Olive. Mediterranean-inspired design with premium finishes throughout, this residence epitomizes refined living.",
    beds: 5,
    baths: 4,
    sqft: 2800,
    amenities: [
      { name: "Wine Cellar", icon: "wine" },
      { name: "Courtyard", icon: "home" },
      { name: "Fountain", icon: "droplet" },
      { name: "Spa", icon: "droplet" },
      { name: "Sauna", icon: "flame" },
      { name: "Terraces", icon: "sun" },
    ],
    floors: [
      { name: "Ground Level", image: "/placeholder-floor-1.jpg" },
      { name: "Main Floor", image: "/placeholder-floor-2.jpg" },
      { name: "Upper Floor", image: "/placeholder-floor-3.jpg" },
    ],
    priceHistory: { labels: ["2020", "2021", "2022", "2023", "2024"], data: [4800, 5500, 6100, 6500, 6800] },
    agent: { name: "Marcus Oliveira", company: "Mediterranean Living", rating: 5 },
  },
  {
    id: 12,
    name: "The Nouveau Villa",
    slug: "the-nouveau-villa",
    location: "Maitama, Abuja",
    price: 8200,
    description: "The ultimate expression of modern luxury. The Nouveau Villa represents the pinnacle of contemporary residential design with cutting-edge technology and bespoke finishes.",
    beds: 7,
    baths: 6,
    sqft: 4200,
    amenities: [
      { name: "Smart Home", icon: "zap" },
      { name: "Home Theater", icon: "film" },
      { name: "Wine Room", icon: "wine" },
      { name: "Spa Suite", icon: "droplet" },
      { name: "Gym", icon: "dumbbell" },
      { name: "Lounge", icon: "chair" },
    ],
    floors: [
      { name: "Ground Floor", image: "/placeholder-floor-1.jpg" },
      { name: "First Floor", image: "/placeholder-floor-2.jpg" },
      { name: "Second Floor", image: "/placeholder-floor-3.jpg" },
    ],
    priceHistory: { labels: ["2020", "2021", "2022", "2023", "2024"], data: [5200, 6200, 7000, 7600, 8200] },
    agent: { name: "Isabelle Laurent", company: "Nouveau Living", rating: 5 },
  },
];

export function getHouseTypeBySlug(slug: string) {
  return houseTypesData.find((house) => house.slug === slug);
}

export function getHouseTypeById(id: number) {
  return houseTypesData.find((house) => house.id === id);
}
